# Generated by Django 4.2.7 on 2024-04-02 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="pdf_file",
            field=models.FileField(null=True, upload_to=""),
        ),
    ]
